### ISSUE TITLE
Fix TLPButton.tsx

### ISSUE THREAD

**Issue by itskarelleh** [itskarelleh/taino-language-app#24]
The title color is not changing, causing the text not to show up. 

Example:
On the onboarding page, the styled button's title color has the value '#fff' but the text in the button is still not showing up.
<img width="1680" alt="Screenshot 2024-10-20 at 12 34 19 PM" src="https://github.com/user-attachments/assets/ccf188c0-f29e-4185-a502-dd46fed45e7c">

Here are the following things that need to be done to complete this issue:
- [x] title color prop should change
 
Additional Notes:
- Don't worry about using the colors for the current prototype. Just ensure that the title color changes

**Comment by Neisha1618** [comment]
My fix for this issue.

![Image](https://github.com/user-attachments/assets/f921e03a-7e2d-4899-8485-fdf8afcccb55)
![Image](https://github.com/user-attachments/assets/cb58de1f-11e5-4365-a3c1-32e764634d71)

**Comment by itskarelleh** [comment]
Amazing 😎

LGTM. Closing issue.
