### ISSUE TITLE
Create Vocabulary Overview screen

### ISSUE THREAD

**Issue by itskarelleh** [itskarelleh/taino-language-app#39]
Here are the following things that need to be done to complete this issue:
- [ ] Translate to reusable prototype

Additional Notes:
- This looks very similar to the screen for when the user completes a lesson in issue #36 so you might want to collab/pair the program with whoever is working on this one.

![Image](https://github.com/user-attachments/assets/756d5066-3df7-42fa-8230-b5662e7ce024)

**Comment by codewithjazzy** [comment]
@Neisha1618 I made mock data for this, for the vocab component in my PR #36.  I'll try to submit it by the weekend

**Comment by Neisha1618** [comment]
@codewithjazzy I appreciate it.

**Comment by itskarelleh** [comment]
@Neisha1618 
The vocab component in PR #36 has been merged into the testing branch 🌈
