### ISSUE TITLE
As a user, I want to sign up with email and password, so I can access the app.

### ISSUE THREAD

**Issue by itskarelleh** [itskarelleh/taino-language-app#73]
# Acceptance criteria

- [x] User is redirected to the welcome screen after sign-up is successful
- [x] New user added to Auth0 application
- [x] User account created after email and password are validated and user clicks on continue button

# Sprint Ready Checklist 
1. - [x] Acceptance criteria defined 
2. - [x] Team understands acceptance criteria 
3. - [x] Acceptance criteria are verifiable/testable 
4. - [x] 3rd-party/external APIs identified

**Comment by Neisha1618** [comment]
@itskarelleh I have a question about this ticket.
